### ISSUE TITLE
Hitting a 404 page crashes the application

### ISSUE THREAD

**Issue by kchung** [gpbl/isomorphic500#28]
I tested out `https://isomorphic500.herokuapp.com/featured/editorss` (extra "s") and it seemed to knock the Heroku app off line:

```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

Development crash callstack: 
```
TypeError: Cannot read property 'isLoading' of null
   at [object Object].render (/mnt/isomorphic500/src/Application.js:59:29)
   at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/mnt/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:767:34)
   at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/mnt/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:793:14)
   at [object Object].wrapper [as _renderValidatedComponent] (/mnt/isomorphic500/node_modules/react/lib/ReactPerf.js:70:21)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/mnt/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:227:30)
   at [object Object].wrapper [as mountComponent] (/mnt/isomorphic500/node_modules/react/lib/ReactPerf.js:70:21)
   at Object.ReactReconciler.mountComponent (/mnt/isomorphic500/node_modules/react/lib/ReactReconciler.js:38:35)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/mnt/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:237:34)
   at [object Object].wrapper [as mountComponent] (/mnt/isomorphic500/node_modules/react/lib/ReactPerf.js:70:21)
   at Object.ReactReconciler.mountComponent (/mnt/isomorphic500/node_modules/react/lib/ReactReconciler.js:38:35)
```

**Comment by gpbl** [comment]
Thanks @kchung ... I should start to work on tests asap :)
