### ISSUE TITLE
Development server crashes on start due to SCSS parsing error

### ISSUE THREAD

**Issue by al3x** [gpbl/isomorphic500#32]
After cloning this repo and running `npm install`, I get the following error when trying to start up the development server:

```
» npm run dev

> isomorphic500@2.0.0 dev /Users/al3x/src/third_party/javascript/isomorphic500
> NODE_ENV=development DEBUG=isomorphic500 node index

  isomorphic500 Intl is not supported, so the polyfill has been loaded. +0ms
/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: /Users/al3x/src/third_party/javascript/isomorphic500/src/style/LocaleSwitcher.scss: Unexpected token (1:0)
> 1 | @import 'constants/colors';
    | ^
  2 | 
  3 | .LocaleSwitcher-link {
  4 |   display: inline-block;
    at Parser.pp.raise (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseDecorator (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:146:10)
    at Parser.pp.parseDecorators (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:132:31)
    at Parser.pp.parseStatement (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:46:10)
    at Parser.parseStatement (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseTopLevel (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:22:21)
    at Object.parse (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/index.js:109:12)
    at module.exports (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/babel/helpers/parse.js:39:21)
    at File.<anonymous> (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/babel/transformation/file/index.js:518:12)

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/al3x/.nvm/versions/io.js/v1.7.1/bin/iojs" "/Users/al3x/.nvm/versions/io.js/v1.7.1/bin/npm" "run" "dev"
npm ERR! node v1.7.1
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
npm ERR! isomorphic500@2.0.0 dev: `NODE_ENV=development DEBUG=isomorphic500 node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isomorphic500@2.0.0 dev script 'NODE_ENV=development DEBUG=isomorphic500 node index'.
npm ERR! This is most likely a problem with the isomorphic500 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development DEBUG=isomorphic500 node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls isomorphic500
npm ERR! There is likely additional logging output above.
```

**Comment by al3x** [comment]
FYI, that previous run was with iojs v1.7.1. Same issue happens with the latest version of Node:

```
» npm run dev

> isomorphic500@2.0.0 dev /Users/al3x/src/third_party/javascript/isomorphic500
> NODE_ENV=development DEBUG=isomorphic500 node index

  isomorphic500 Intl has been found, but locale data has been polyfilled. +0ms
/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/babel/helpers/parse.js:70
    throw err;
          ^
SyntaxError: /Users/al3x/src/third_party/javascript/isomorphic500/src/style/LocaleSwitcher.scss: Unexpected token (1:0)
> 1 | @import 'constants/colors';
    | ^
  2 | 
  3 | .LocaleSwitcher-link {
  4 |   display: inline-block;
    at Parser.pp.raise (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/location.js:68:13)
    at Parser.pp.unexpected (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseDecorator (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:146:10)
    at Parser.pp.parseDecorators (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:132:31)
    at Parser.pp.parseStatement (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:46:10)
    at Parser.parseStatement (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/plugins/flow.js:631:22)
    at Parser.pp.parseTopLevel (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/statement.js:22:21)
    at Object.parse (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/acorn/src/index.js:109:12)
    at module.exports (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/babel/helpers/parse.js:39:21)
    at File.<anonymous> (/Users/al3x/src/third_party/javascript/isomorphic500/node_modules/babel-core/lib/babel/transformation/file/index.js:518:12)

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/al3x/.nvm/versions/node/v0.12.2/bin/node" "/Users/al3x/.nvm/versions/node/v0.12.2/bin/npm" "run" "dev"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! isomorphic500@2.0.0 dev: `NODE_ENV=development DEBUG=isomorphic500 node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isomorphic500@2.0.0 dev script 'NODE_ENV=development DEBUG=isomorphic500 node index'.
npm ERR! This is most likely a problem with the isomorphic500 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development DEBUG=isomorphic500 node index
npm ERR! You can get their info via:
npm ERR!     npm owner ls isomorphic500
npm ERR! There is likely additional logging output above.
```

**Comment by iam4x** [comment]
Hey @al3x 

I think it's the same issue we had there: https://github.com/iam4x/isomorphic-flux-boilerplate/issues/16

You maybe have a `BROWSER` env variable in your system, the workaround is to:

```
delete process.env.BROWSER
```

on the first line of the server file (https://github.com/gpbl/isomorphic500/blob/master/webpack/server.js)

**Comment by gpbl** [comment]
Hi @al3x, thanks for the PR and thanks @iam4x for the help! 
Indeed I could reproduce the issue running `BROWSER=open npm run dev`
Is that env variable set when installing iojs? I've never seen it before.

**Comment by al3x** [comment]
@gpbl Nope, it's set by some shell enhancement libraries like oh-my-zsh and zprezto. Some command line tools on Mac OS X will look for the `$BROWSER` environment variable, and setting to `open` makes use of the default browser on the system. Thanks for merging!

**Comment by mmahalwy** [comment]
Anyone still having this problem?!

**Comment by gpbl** [comment]
@mmahalwy make sure you use node 4 and updated dependencies. Earlier versions of node-sass were highly unstable :/

**Comment by mmahalwy** [comment]
@gpbl interesting.... I didnt know node 4 is out! I am still on 0.12.7....

**Comment by mmahalwy** [comment]
@gpbl tried it an no luck

```
/Users/mmahalwy/Sites/new-pirate/src/styles/app.scss:1
(function (exports, require, module, __filename, __dirname) { body{
                                                                  ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mmahalwy/Sites/new-pirate/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mmahalwy/Sites/new-pirate/src/components/Application.js:2:1)
    at Module._compile (module.js:434:26)
6 Oct 01:36:54 - [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by gpbl** [comment]
@mmahalwy could you please post your `Application.js` and the webpack config you are using? It seems you are importing the .scss file from node.

**Comment by mmahalwy** [comment]
@gpbl I am trying to do that, yes. I have an isomorphic app with Application.js being loaded both on server and client - thoughts about how to handle it only on the client?

**Comment by gpbl** [comment]
@mmahalwy you can't require scss files from node.js, they are intended to work only on build time. Hence, you must write:

```js
// Application.js
if (process.env.BROWSER) {
  require('../style/Application.scss');
}
```

and make sure you have that env variable set in your webpack config via the define plugin ([example](https://github.com/gpbl/isomorphic500/blob/master/webpack/dev.config.js#L38-L43)).

**Comment by mmahalwy** [comment]
@gpbl yep, I adopted that now! 

My only challenge is I'd love to use css-loader's local scopes https://github.com/webpack/css-loader#local-scope and I cannot do that nicely with `process.env.BROWSER`  :(

**Comment by gpbl** [comment]
I don't know a solution for this case in an isomorphic env, @mmahalwy. I'd try build the server-side code with webpack as well: however, I don't think its worth the hassle 😴

**Comment by mmahalwy** [comment]
@gpbl https://www.npmjs.com/package/webpack-isomorphic-tools is the answer but it can be challenging to setup to begin with
