### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by juancabrera** [gpbl/isomorphic500#73]
When I run `npm run dev` it works fine, but when I hit the URL on browser I'm getting this error (got same error on `npm run built`):

```
TypeError: Cannot read property 'map' of undefined
    at HtmlDocument.render (/Users/cabrera/htdocs/juan/isomorphic500/src/server/HtmlDocument.js:59:19)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at [object Object].wrapper [as _renderValidatedComponent] (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactPerf.js:70:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at [object Object].wrapper [as mountComponent] (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at [object Object].wrapper [as mountComponent] (/Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactPerf.js:70:21)
    at /Users/cabrera/htdocs/juan/isomorphic500/node_modules/react/lib/ReactServerRendering.js:68:32
```

The error is coming from [here](https://github.com/gpbl/isomorphic500/blob/master/src/server/HtmlDocument.js#L59), on HtmlDocument.js:59:19
```
          { images.map(url => <meta property="og:image" content={ url } />) } 
```

I'm running node `v0.12.4`

**Comment by gpbl** [comment]
Yes you are right, thanks for reporting this! Let me check what went wrong ... :-)

**Comment by gpbl** [comment]
It is because [this issue](https://github.com/babel/babel/issues/2086) with babel. I just pushed an update using a previous version of babel: please pull, clean up `node_modules` and run `npm install` to get it running again :-)

```
git pull
rm -rf node_modules
npm install
```

As the issue with babel get fixed, we can move again to the latest version.

**Comment by juancabrera** [comment]
thank you so much @gpbl, works perfect now :smile:

**Comment by gpbl** [comment]
It [should be fixed](https://twitter.com/sebmck/status/626009657270734848) with the last babel, however :-)

**Comment by juancabrera** [comment]
yes! tested it and all working fine.

created #74.
