### ISSUE TITLE
Can't run "17 error isomorphic500@2.0.0 dev: `NODE_ENV=development DEBUG=isomorphic500 nodemon index.js`"

### ISSUE THREAD

**Issue by roskom** [gpbl/isomorphic500#75]
node -v = v0.12.7 
I've used this guide:
git clone https://github.com/gpbl/isomorphic500.git
cd isomorphic500
npm install
 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev isomorphic500@2.0.0
6 info dev isomorphic500@2.0.0
7 verbose unsafe-perm in lifecycle true
8 info isomorphic500@2.0.0 Failed to exec dev script
9 verbose stack Error: isomorphic500@2.0.0 dev: `NODE_ENV=development DEBUG=isomorphic500 nodemon index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid isomorphic500@2.0.0
11 verbose cwd C:\proj\isomorphic500
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error isomorphic500@2.0.0 dev: `NODE_ENV=development DEBUG=isomorphic500 nodemon index.js`
17 error Exit status 1
18 error Failed at the isomorphic500@2.0.0 dev script 'NODE_ENV=development DEBUG=isomorphic500 nodemon index.js'.
18 error This is most likely a problem with the isomorphic500 package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=development DEBUG=isomorphic500 nodemon index.js
18 error You can get their info via:
18 error     npm owner ls isomorphic500
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by gpbl** [comment]
Hi @roskom it seems like the same issue described [here](https://github.com/gpbl/isomorphic500/issues/58) ... I should definitely add a note for Windows users :-)
